# Generated by Django 6.1.1 on 2026-09-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Video name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('wallpaper', models.ImageField(blank=True, help_text='Preview image shown in the catalog. Leave empty to use a placeholder.', upload_to='wallpapers/', verbose_name='Wallpaper / poster')),
                ('video_url', models.URLField(help_text='Yandex Cloud Video player link (e.g. https://runtime.strm.yandex.ru/player/vplvXXXXXX) or a direct media file URL (mp4, webm, ...).', verbose_name='Link to storage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
