# Generated by Django 6.1.1 on 2026-09-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, help_text='Can be left empty: when saving with auto-fill enabled it is fetched from the storage link.', max_length=200, verbose_name='Video name'),
        ),
    ]
